stages:
  download_2025_data:
    cmd: python download.py
    deps:
      - download.py
    outs:
      - data/archives.gov/2025

  extract:
    cmd: python extract.py
    deps:
      - extract.py
      - prompts/extraction/instructions.txt
      - prompts/extraction/system.txt
      - data/archives.gov
    params:
      - .config/default.json:
          - extraction
    outs:
      - data/extracted